### ISSUE TITLE
setPrivateData not working

### ISSUE THREAD

**Issue by sulphur** [legastero/stanza#137]
Hi,

I have a problem with settingPrivateData. Mu ejabberd server has `mod_private' enabled.

What i try to do is :

```
this.client.setPrivateData({myDataStore: {name: "some_name"}})
```

however in raw `iq` request thre is no custom data present. 

```
<iq xmlns="jabber:client" type="get" id="53edd7c8-b909-44ce-9903-174fbc0c7d42"><query xmlns="jabber:iq:private"/></iq>
```

which result in 406 response. 

The same way for example when i try to `get` bookmarks i have a response but when i try to getPrivateData({bookmarks2: true}) i get 406 resonse and my iq request querry is empty as well 

```
<iq xmlns="jabber:client" type="get" id="c9179128-7bd4-4513-b469-13cf3cefe532"><query xmlns="jabber:iq:private"/></iq>
```

Do i need to create a store os sth ? Someone know how it should work ?

best regards
Piotr

**Comment by przemyslawjanpietrzak** [comment]
+1

**Comment by dPeS** [comment]
+1

**Comment by przemyslawjanpietrzak** [comment]
I get it! In jxt-xmpp/private.js <a href="https://github.com/otalk/jxt-xmpp/blob/314411456ecacdfb38e85291b3bae34e17273840/src/private.js">link</a> query has no children, but in xep-0049 need to have <a href="http://xmpp.org/extensions/xep-0049.html">link</a>.

I should write pull request with it in next 2-3 days.

**Comment by sulphur** [comment]
why did you manage to get it working ?

**Comment by cveilleux** [comment]
To anyone stumbling on this problem, the setPrivateData function does work. It is used internally by the bookmarks plugin and it does work.

It cannot be used on its own: You need to define support for your private XML schema that you want to store, otherwise it will be silently dropped by setPrivateData and you end up with nothing sent to the server.

The solution is to write a custom [plugin](https://github.com/legastero/stanza.io/blob/master/docs/Create_Plugin.md)

Here is an example that can store any javascript object in private storage on the server and get it back:

https://gist.github.com/cveilleux/ae1f8b9f6186a1a5150f5826ec5e10b7

Just register the plugin when you create the stanza client ( `client.use(require('path/to/plugin'));` )

You can then use it like this:

 ```
 var docs = {doc1: 'some value', doc2: {some: 'value'}, doc3: ['some', 'value']};
 client.setPrivateDocuments(docs, cb);
 client.getPrivateDocuments(cb);
 ```
