### ISSUE TITLE
pubsub:event items have no contents

### ISSUE THREAD

**Issue by polymeris** [legastero/stanza#440]
So, looking at the wire I get this over WS:
```xml
<message xmlns='jabber:client' to='1f50e3b2-da60-4bb6-ae2c-0d64e4f0e14f@example.dev'
         from='test-room@conference.example.dev' id='15736420007677086092'>
    <event xmlns='http://jabber.org/protocol/pubsub#event'>
        <items node='urn:xmpp:mucsub:nodes:messages'>
            <item id='15736420007677086092'>
                <message xml:lang='en' to='1f50e3b2-da60-4bb6-ae2c-0d64e4f0e14f@example.dev'
                         from='test-room@conference.example.dev/hey' type='groupchat'
                         id='id21ed0844-3542-4dad-a002-a8fac6ce4ec2' xmlns='jabber:client'>
                    <active xmlns='http://jabber.org/protocol/chatstates'/>
                    <origin-id xmlns='urn:xmpp:sid:0' id='id21ed0844-3542-4dad-a002-a8fac6ce4ec2'/>
                    <body>Hello, World!</body>
                </message>
            </item>
        </items>
    </event>
</message>
```

The `PubsubEventMessage` passed to "pubsub:event", however, looks like this:
```json
{
  "from": "test-room@conference.example.dev",
  "id": "15736420007677086092",
  "lang": "",
  "to": "1f50e3b2-da60-4bb6-ae2c-0d64e4f0e14f@example.dev",
  "pubsub": {
    "context": "event",
    "eventType": "items",
    "items": {
      "node": "urn:xmpp:mucsub:nodes:messages",
      "retracted": [],
      "published": [
        {
          "id": "15736420007677086092"
        }
      ]
    }
  }
}
```

Note how the published item only contains an id, there is no message, body, etc.

I have tried with a bunch of variations of `.define`ing things in the registry, but to no avail (I am not even sure if that should be necessary, no special treatment seems to be given to e.g. [this test case](https://github.com/legastero/stanza/blob/master/test/protocol-cases/xep0060/publish-event-payload.xml)

Any hints as to what I might be doing wrong?

**Comment by polymeris** [comment]
Oh, turns out that case *is* given special treatment in https://github.com/legastero/stanza/blob/master/src/protocol/rfc4287.ts

`.define`ing this is enough:

```
{:aliases (stanza/JXT.pubsubItemContentAliases)
 :element "message"
 :namespace "jabber:client"
 :type "jabber:client"
 :typeField "itemType"}
```

**Comment by legastero** [comment]
This is based on https://docs.ejabberd.im/developer/xmpp-clients-bots/extensions/muc-sub/, which Stanza does not natively support. In part, precisely because of this exact problem.

Mucsub uses message and presence elements as pubsub item content without any additional wrapping element to indicate it is mucsub content.

Handling that requires an additional degree of flexibility than Stanza allows in its XML/JSON mapping right now. It would require JXT to determine JSON and XML outputs based on the combination of 2 type fields, instead of the 1 type field it currently uses. (In this case, messages already have `streamType` as their type field, which precludes using `itemType` as the type field as expected for pubsub content.)

You can almost make it work, but it _will_ break other definitions.

The simplest mapping that works to get mucsub running is to use:
```
stanzas.define({
  element: 'message',
  namespace: NS_CLIENT,
  path: 'pubsubeventitem.mucsubMessage'
});
stanzas.define({
  element: 'presence',
  namespace: NS_CLIENT,
  path: 'pubsubeventitem.mucsubPresence'
});
```

But even that breaks the convention for pubsub events by needing to check the item for new `mucsubMessage`/`mucsubPresence` field instead of looking in the `content` field.

**Comment by polymeris** [comment]
Thanks for the exhaustive answer, @legastero! As you can probably tell, I am only starting to understand this whole XMPP/stanza stuff.

Having to check for the `.mucsubMessage`/`.mucsubPresence` fields on pubsub events might be less elegant than relying on standard `.content`, but it's manageable.

Other than that, what can I expect to break?
